name: Release

on:
  push:
    tags:
      - "v*" # Trigger on tags like v1.0.0

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-C target-cpu=native"

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: disk-usage-tui-linux-x86_64
            output_name: disk-usage-tui
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: disk-usage-tui-macos-aarch64
            output_name: disk-usage-tui
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: disk-usage-tui-windows-x86_64.exe
            output_name: disk-usage-tui.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-


      - name: Build release binary
        shell: bash
        run: |
          cargo build --release --target ${{ matrix.target }}
          mkdir -p release
          cp target/${{ matrix.target }}/release/${{ matrix.output_name }} release/${{ matrix.artifact_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: release/${{ matrix.artifact_name }}
          retention-days: 1

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List files for debugging
        run: find artifacts -type f

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Disk Usage TUI Analyzer ${{ github.ref_name }}

            ### Assets
            - `disk-usage-tui-linux-x86_64` - Linux x86_64
            - `disk-usage-tui-macos-aarch64` - macOS (Apple Silicon)
            - `disk-usage-tui-windows-x86_64.exe` - Windows x86_64
          draft: false
          prerelease: false
          files: |
            artifacts/disk-usage-tui-linux-x86_64
            artifacts/disk-usage-tui-macos-aarch64
            artifacts/disk-usage-tui-windows-x86_64.exe
